### ISSUE TITLE
Unable to compile using gcc version 14.2.0

### ISSUE THREAD

**Issue by VOC-LINK** [Terraspace/HJWasm#232]
During a compilation attempt it breaks with an error:

In file included from assemble.c:18:
assemble.c: In function 'get_module_name':
H/globals.h:51:17: error: implicit declaration of function 'strupr'; did you mean '_strupr'? [-Wimplicit-function-declaration]
   51 | #define _strupr strupr
      |                 ^~~~~~
Also several warnings are present before and later.

gcc version 14.2.0 (GCC), Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, Linux Slackware 15.0
